import {
  type User,
  type Trip,
  type Booking,
  type PanicAlert,
  type Rating,
  UserRole,
  KycStatus,
  TripStatus,
  BookingStatus,
  PanicType,
} from "@/types"

export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "john.passenger@example.com",
    phone: "+1234567890",
    password: "hashed_password",
    fullName: "John Doe",
    role: UserRole.PASSENGER,
    kyc: {
      id: "kyc-1",
      nin: "12345678901",
      status: KycStatus.VERIFIED,
      verifiedBy: "admin-1",
      verifiedAt: new Date("2024-01-15"),
      createdAt: new Date("2024-01-10"),
      updatedAt: new Date("2024-01-15"),
    },
    bookings: [],
    ratings: [],
    panicAlerts: [],
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "user-2",
    email: "mike.driver@example.com",
    phone: "+1234567891",
    password: "hashed_password",
    fullName: "Mike Johnson",
    role: UserRole.DRIVER,
    kyc: {
      id: "kyc-2",
      nin: "12345678902",
      license: "DL123456789",
      policeClearance: "PC987654321",
      status: KycStatus.VERIFIED,
      verifiedBy: "admin-1",
      verifiedAt: new Date("2024-01-20"),
      createdAt: new Date("2024-01-12"),
      updatedAt: new Date("2024-01-20"),
    },
    driverProfile: {
      id: "driver-1",
      trips: [],
    },
    bookings: [],
    ratings: [],
    panicAlerts: [],
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "user-3",
    email: "admin@transport.com",
    phone: "+1234567892",
    password: "hashed_password",
    fullName: "Sarah Admin",
    role: UserRole.ADMIN,
    kyc: {
      id: "kyc-3",
      nin: "12345678903",
      status: KycStatus.VERIFIED,
      verifiedBy: "system",
      verifiedAt: new Date("2024-01-01"),
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    bookings: [],
    ratings: [],
    panicAlerts: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const mockTrips: Trip[] = [
  {
    id: "trip-1",
    driverId: "driver-1",
    origin: "Lagos",
    destination: "Abuja",
    departureTime: new Date("2024-02-15T08:00:00"),
    arrivalTime: new Date("2024-02-15T16:00:00"),
    status: TripStatus.SCHEDULED,
    bookings: [],
    panicAlerts: [],
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "trip-2",
    driverId: "driver-1",
    origin: "Abuja",
    destination: "Kano",
    departureTime: new Date("2024-02-16T09:00:00"),
    status: TripStatus.IN_PROGRESS,
    bookings: [],
    panicAlerts: [],
    createdAt: new Date("2024-02-02"),
    updatedAt: new Date("2024-02-16"),
  },
]

export const mockBookings: Booking[] = [
  {
    id: "booking-1",
    tripId: "trip-1",
    passengerId: "user-1",
    qrCode: "QR123456789",
    status: BookingStatus.CONFIRMED,
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
    trip: mockTrips[0],
    passenger: mockUsers[0],
  },
]

export const mockPanicAlerts: PanicAlert[] = [
  {
    id: "panic-1",
    userId: "user-1",
    tripId: "trip-2",
    type: PanicType.PASSENGER,
    message: "Emergency assistance needed",
    resolved: false,
    createdAt: new Date("2024-02-16T10:30:00"),
    user: mockUsers[0],
  },
]

export const mockRatings: Rating[] = [
  {
    id: "rating-1",
    passengerId: "user-1",
    tripId: "trip-1",
    score: 5,
    comment: "Excellent service, very punctual!",
    createdAt: new Date("2024-02-15T17:00:00"),
    passenger: mockUsers[0],
    trip: mockTrips[0],
  },
  {
    id: "rating-2",
    passengerId: "user-1",
    tripId: "trip-2",
    score: 4,
    comment: "Good trip overall, comfortable seats.",
    createdAt: new Date("2024-02-16T18:30:00"),
    passenger: mockUsers[0],
    trip: mockTrips[1],
  },
]
